/* ------------------------------------------------------------------ */
/*  Sätze  (nur LCWO-Zeichen: A-Z, 0-9, . , ? / = + - @ ; : ( ))     */
/* ------------------------------------------------------------------ */
const SENTENCES = [
  // Deutsch — Alltag
  { c:'de', s:"Das Leben ist so schoen." },
  { c:'de', s:"Heute scheint die Sonne." },
  { c:'de', s:"Der Hund bellt sehr laut." },
  { c:'de', s:"Ich lerne Morse jeden Tag." },
  { c:'de', s:"Wir fahren morgen nach Berlin." },
  { c:'de', s:"Die Katze liegt auf dem Sofa." },
  { c:'de', s:"Das Wetter ist heute sehr gut." },
  { c:'de', s:"Der Zug faehrt bald ab." },
  { c:'de', s:"Das Kind spielt im Garten." },
  { c:'de', s:"Ich trinke Kaffee am Morgen." },
  { c:'de', s:"Guten Morgen lieber Freund." },
  { c:'de', s:"Die Schule beginnt um neun Uhr." },
  { c:'de', s:"Ein schoener Tag fuer uns alle." },
  { c:'de', s:"Morgen kommt ein Paket an." },
  { c:'de', s:"Mein Name ist Hans." },
  { c:'de', s:"Die Sonne scheint den ganzen Tag." },
  { c:'de', s:"Er liest jeden Abend ein Buch." },
  { c:'de', s:"Das Essen ist fertig." },
  { c:'de', s:"Wir treffen uns um fuenf Uhr." },
  { c:'de', s:"Die Bruecke ist sehr alt." },
  { c:'de', s:"Er faehrt jeden Tag mit dem Rad." },
  { c:'de', s:"Das Fenster ist offen." },
  { c:'de', s:"Sie singt ein schoenes Lied." },
  { c:'de', s:"Der Arzt kommt um zehn Uhr." },
  { c:'de', s:"Das Auto steht vor dem Haus." },
  { c:'de', s:"Wir essen heute Suppe." },
  { c:'de', s:"Das Wasser ist kalt." },
  { c:'de', s:"Der Brief ist schon abgeschickt." },
  { c:'de', s:"Er schlaeft noch." },
  { c:'de', s:"Die Blumen bluehen im Fruehling." },
  { c:'de', s:"Das Brot ist frisch gebacken." },
  { c:'de', s:"Heute ist Montag." },
  { c:'de', s:"Der Weg ist lang aber schoen." },
  { c:'de', s:"Sie lernt jeden Tag Vokabeln." },
  { c:'de', s:"Das Museum ist dienstags geschlossen." },
  { c:'de', s:"Er arbeitet in einer Fabrik." },
  { c:'de', s:"Die Kinder spielen Ball." },
  { c:'de', s:"Wir wohnen nahe am See." },
  { c:'de', s:"Das Konzert beginnt um acht." },
  { c:'de', s:"Der Markt findet samstags statt." },
  // Deutsch — Wetter
  { c:'de', s:"Es regnet den ganzen Tag." },
  { c:'de', s:"Morgen wird es schneit." },
  { c:'de', s:"Der Wind weht sehr stark." },
  { c:'de', s:"Es gibt Gewitter am Abend." },
  { c:'de', s:"Der Nebel liegt im Tal." },
  { c:'de', s:"Im Winter ist es kalt und dunkel." },
  { c:'de', s:"Der Schnee liegt noch auf dem Berg." },
  { c:'de', s:"Die Temperatur steigt auf dreissig Grad." },
  { c:'de', s:"Es ist bewoelkt und kuehl." },
  { c:'de', s:"Der Herbst bringt bunte Blaetter." },
  // Deutsch — Amateurfunk / CW
  { c:'de', s:"CQ DE {CALL} K" },
  { c:'de', s:"73 DE {CALL}" },
  { c:'de', s:"Der Funkamateur sendet heute." },
  { c:'de', s:"Viele Gruesse aus der Schweiz." },
  { c:'de', s:"Fritz sendet Morse seit Jahren." },
  { c:'de', s:"Mein Rufzeichen ist {CALL}." },
  { c:'de', s:"Die Antenne steht auf dem Dach." },
  { c:'de', s:"Ich hoere euch sehr gut." },
  { c:'de', s:"Das Signal ist stark und klar." },
  { c:'de', s:"QSL DE {CALL} 73." },
  { c:'de', s:"Der Contest laeuft bis Sonntag." },
  { c:'de', s:"Ich sende auf vierzig Meter." },
  { c:'de', s:"Das Geraet laeuft einwandfrei." },
  { c:'de', s:"Die Verbindung ist sehr gut." },
  { c:'de', s:"Bitte nochmals etwas langsamer." },
  { c:'de', s:"Ich empfange dich fuenf und neun." },
  { c:'de', s:"Der Pegel ist etwas zu hoch." },
  { c:'de', s:"Wir haben Skype ersetzt durch Funk." },
  { c:'de', s:"Der Transceiver ist neu." },
  { c:'de', s:"Das Logbuch ist vollgeschrieben." },
  { c:'de', s:"Ich fahre morgen zur Bergstation." },
  { c:'de', s:"Der Dipol haengt zwischen zwei Baeumen." },
  { c:'de', s:"Die SWR ist fast eins zu eins." },
  { c:'de', s:"Ich arbeite mit hundert Watt." },
  { c:'de', s:"Der Kurzwellenempfaenger laeuft gut." },
  // Deutsch — Reise / Natur
  { c:'de', s:"Die Berge sind mit Schnee bedeckt." },
  { c:'de', s:"Der See glaenzt in der Sonne." },
  { c:'de', s:"Wir wandern morgen auf den Gipfel." },
  { c:'de', s:"Das Tal ist sehr tief und schmal." },
  { c:'de', s:"Die Voegl singen frueh am Morgen." },
  { c:'de', s:"Der Wald riecht nach Harz." },
  { c:'de', s:"Am Abend leuchtet das Alpengluehn." },
  { c:'de', s:"Der Fluss fliesst ruhig ins Meer." },
  { c:'de', s:"Die Wanderung dauert vier Stunden." },
  { c:'de', s:"Am Horizont sieht man die Berge." },
  { c:'de', s:"Das Tal liegt noch im Schatten." },
  { c:'de', s:"Wir uebernachten in der Huette." },
  { c:'de', s:"Der Gipfel ist fast zweitausend Meter hoch." },
  { c:'de', s:"Der Adler kreist ueber dem Felsen." },
  { c:'de', s:"Im Herbst faerben sich die Blaetter." },
  // Deutsch — Technik
  { c:'de', s:"Der Computer startet sehr langsam." },
  { c:'de', s:"Das Programm hat einen Fehler." },
  { c:'de', s:"Die Batterie ist fast leer." },
  { c:'de', s:"Der Drucker braucht neues Papier." },
  { c:'de', s:"Das Netz ist heute sehr langsam." },
  { c:'de', s:"Er installiert das neue System." },
  { c:'de', s:"Die Festplatte ist voll." },
  { c:'de', s:"Das Kabel ist zu kurz." },
  { c:'de', s:"Der Bildschirm flimmert manchmal." },
  { c:'de', s:"Das Update dauert noch zehn Minuten." },
  // English — Everyday
  { c:'en', s:"The weather is very fine today." },
  { c:'en', s:"My name is Peter." },
  { c:'en', s:"Good morning from Switzerland." },
  { c:'en', s:"The signal is very strong here." },
  { c:'en', s:"I am listening on this frequency." },
  { c:'en', s:"Thanks for the contact." },
  { c:'en', s:"See you on the bands." },
  { c:'en', s:"Best 73 and good dx." },
  { c:'en', s:"The sun is shining today." },
  { c:'en', s:"Hello from my station." },
  { c:'en', s:"The cat is on the roof." },
  { c:'en', s:"We went hiking in the mountains." },
  { c:'en', s:"The train arrives at noon." },
  { c:'en', s:"Please send your report." },
  { c:'en', s:"I copy you five and nine." },
  { c:'en', s:"The antenna is on the tower." },
  { c:'en', s:"My rig is running fine." },
  { c:'en', s:"The log is almost full." },
  { c:'en', s:"We had a great contest." },
  { c:'en', s:"The battery is running low." },
  { c:'en', s:"Good night and 73." },
  { c:'en', s:"The dog is barking loudly." },
  { c:'en', s:"She sings a beautiful song." },
  { c:'en', s:"The river flows to the sea." },
  { c:'en', s:"I drink coffee every morning." },
  // Punctuation — ,.?=/=
  { c:'punct', s:"CQ CQ = DE {CALL} = PSE K" },
  { c:'punct', s:"How are you? Fine, thanks." },
  { c:'punct', s:"What is your name? My name is Peter." },
  { c:'punct', s:"RST = 599. QTH = Zurich." },
  { c:'punct', s:"Is the frequency clear? Yes, go ahead." },
  { c:'punct', s:"Hello, how are you today?" },
  { c:'punct', s:"DR OM = TNX FER CALL = 73 DE {CALL}" },
  { c:'punct', s:"UR RST = 579. PWR = 100 W." },
  { c:'punct', s:"CQ DX = DE {CALL} = QRP K" },
  { c:'punct', s:"GM OM, HW CPI? PSE QRS." },
  { c:'punct', s:"TNX = 73 = GL = CUL = {CALL}" },
  { c:'punct', s:"QSL? = YES = FULL CALL HRD = OK?" },
  { c:'punct', s:"WX = FINE. ANT = DIPOLE 40M." },
  { c:'punct', s:"OP = PETER. QTH = BERN. PWR = 5 W." },
  { c:'punct', s:"TEST, TEST. CQ? DE {CALL} = K" },
  // Callsigns: dynamisch generiert via generateCallsign() in app.js
  // Numbers
  { c:'num', s:"7 8 9 0 1 2" },
  { c:'num', s:"3 1 4 1 5 9" },
  { c:'num', s:"2 7 1 8 2 8" },
  { c:'num', s:"99 73 55 33 11 88" },
  { c:'num', s:"14 21 35 57 92 64" },
  { c:'num', s:"599 001 14225 100 73 88" },
  { c:'num', s:"365 24 60 60 1000 42" },
  { c:'num', s:"15 27 38 49 50 61" },
  { c:'num', s:"5 10 15 20 25 30" },
  { c:'num', s:"404 200 301 500 403 204" },
  { c:'num', s:"9 18 27 36 45 54" },
  { c:'num', s:"3 6 9 12 15 18" },
  { c:'num', s:"42 17 83 05 61 29" },
  { c:'num', s:"11 22 33 44 55 66" },
  { c:'num', s:"70 144 432 1296 50 28" },
  // Q-Codes
  { c:'qcode', s:"QRZ? DE {CALL} K" },
  { c:'qcode', s:"QTH BERN QSL 73" },
  { c:'qcode', s:"QRM QRN QSB PSE QRS" },
  { c:'qcode', s:"QSL 73 DE {CALL}" },
  { c:'qcode', s:"QRP 5W QTH ZURICH" },
  { c:'qcode', s:"QRO 100W ANT DIPOL" },
  { c:'qcode', s:"QSY 14225 QRV K" },
  { c:'qcode', s:"QRX 5 MIN QRL?" },
  { c:'qcode', s:"QRT 73 DE {CALL}" },
  { c:'qcode', s:"QSO NR 123 QSL?" },
  { c:'qcode', s:"QTH LOC JN36 73" },
  { c:'qcode', s:"QRK 5 QSA 9 73" },
  { c:'qcode', s:"QRL? DE {CALL} K" },
  { c:'qcode', s:"QSK QSO QSL QTH K" },
  { c:'qcode', s:"QRZ {CALL} DE {CALL}" },
  { c:'qcode', s:"QNI DE {CALL} PSE" },
  { c:'qcode', s:"QSB QRM 73 PSE RPT" },
  { c:'qcode', s:"QRN UR QRM QSB FB" },
  { c:'qcode', s:"QSP VIA {CALL} K" },
  { c:'qcode', s:"QRQ PSE QRS UR QRM" },
  // Prosigns: + = <AR>, = = <BT>, ( = <KN>, & = <AS>, ~ = <SK>
  { c:'prosign', s:"CQ DE {CALL} + K" },
  { c:'prosign', s:"{CALL} DE {CALL} + KN" },
  { c:'prosign', s:"CQ CQ DE {CALL} {CALL} + K" },
  { c:'prosign', s:"{CALL} DE {CALL} = UR RST 599 = QTH BERN + KN" },
  { c:'prosign', s:"DR OM = TNX FER CALL = 73 + KN" },
  { c:'prosign', s:"{CALL} DE {CALL} = NAME HANS = QTH BERN = HW? + KN" },
  { c:'prosign', s:"TNX FER QSO = GL 73 DE {CALL} ~ E E" },
  { c:'prosign', s:"73 DE {CALL} = CUL ~ E E" },
  { c:'prosign', s:"{CALL} DE {CALL} ~ TU 73" },
  { c:'prosign', s:"QRX 5 MIN &" },
  { c:'prosign', s:"PSE & QRV IN 2 MIN" },
  { c:'prosign', s:"= ANT DIPOL = PWR 5W + KN" },
  { c:'prosign', s:"= RST 579 = QTH ZURICH = HW? + KN" },
  { c:'prosign', s:"= PWR 100W = ANT YAGI = FB + KN" },
  { c:'prosign', s:"CQ DX DE {CALL} + K" },
  { c:'prosign', s:"PSE RPT NAME & = OK GO AHD + KN" },
  { c:'prosign', s:"= TNX = 73 = GL ~ E E" },
  { c:'prosign', s:"{CALL} {CALL} DE {CALL} + K" },
  { c:'prosign', s:"QSL TNX 73 DE {CALL} ~ E E" },
  { c:'prosign', s:"= SRI QRM = PSE RPT + KN" },
];

/* ------------------------------------------------------------------ */
/*  Morse-Dekodier-Tabelle                                             */
/* ------------------------------------------------------------------ */
const MORSE = {
  '.-':'A',    '-...':'B',  '-.-.':'C',  '-..':'D',   '.':'E',
  '..-.':'F',  '--.':'G',   '....':'H',  '..':'I',    '.---':'J',
  '-.-':'K',   '.-..':'L',  '--':'M',    '-.':'N',    '---':'O',
  '.--.':'P',  '--.-':'Q',  '.-.':'R',   '...':'S',   '-':'T',
  '..-':'U',   '...-':'V',  '.--':'W',   '-..-':'X',  '-.--':'Y',
  '--..':'Z',
  '-----':'0', '.----':'1', '..---':'2', '...--':'3', '....-':'4',
  '.....':'5', '-....':'6', '--...':'7', '---..':'8', '----.':'9',
  '.-.-.-':'.',  '--..--':',',  '..--..':'?',  '-..-.':'/',
  '-...-':'=',   '.-.-.':'+',   '-....-':'-',  '.--.-':'@',
  '-.-.-.':';',  '---...':':',  '-.--.':'(',   '-.--.-':')',
  '.-...':'&',   '...-.-':'~',   '........':'<HH>',
};
// Reverse lookup char → code
const MORSE_REV = {};
for (const [code, ch] of Object.entries(MORSE)) MORSE_REV[ch] = code;

// Koch method character order (LCWO sequence, levels 1-48)
const KOCH_ORDER = 'KMRSUAPTLOWI.NJEF0Y,VG5/Q9ZH38B?427C1D6X=+-@;:()';
